version: "3"
services:
  generator:
    image: generator
    entrypoint: node
    command:
      - index.js
    depends_on:
      - tcc_loader
      - postgres
    volumes:
      - ./:/generator/
    networks:
      - etl_network
  tcc_loader:
    image: tcc_loader
    entrypoint: "sanic"
    command: ["main:app", "--host=0.0.0.0", "--port=1997", "--workers=1", "-r", "-d"]
    ports:
      - "1997:1997"
    volumes:
      - /home/arthuregide/projects/tcc/python_loader/:/sanic
    networks:
      - etl_network
  postgres:
    image: postgres:11
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: arthur
      POSTGRES_PASSWORD: egide
      POSTGRES_DB: db
    networks:
      - etl_network
networks:
  etl_network:
    driver: bridge